---
name: Git Flow

on:
  - pull_request
  - push

jobs:
  GitFlow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Retrieve Release Candidate Name
        run: echo "RELEASE_CANDIDATE_TAG=$( cat VERSION )" >> $GITHUB_OUTPUT
        id: version

      - name: Git Flow Action
        uses: cbdq-io/gitflow-action@feature/mvp
        env:
          # Setting this environment variable means we can debug by re-running
          # workflows and ticking "Enable debug logging".
          ACTIONS_RUNNER_DEBUG: ${{ runner.debug }}
        with:
          release-candidate: ${{ steps.version.RELEASE_CANDIDATE_TAG }}
