---
name: Git Flow

env:
  ACTIONS_RUNNER_DEBUG: ${{ runner.debug }}
on:
  - pull_request
  - push

jobs:
  GitFlow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Git Flow Action
        uses: cbdq-io/gitflow-action@feature/mvp
